# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore NeaServer.sln
    - name: Build
      run: dotnet build NeaServer.csproj --no-restore --self-contained
      
    - uses: actions/upload-artifact@v3
      with:
        name: Server Build
        path: bin/Debug/net7.0/*
